GET http://localhost:3000/api/geotags HTTP/1.1

###
POST http://localhost:3000/api/geotags HTTP/1.1

###
GET http://localhost:3000/api/geotags/:id HTTP/1.1

###
PUT http://localhost:3000/api/geotags/:id HTTP/1.1

###
DELETE http://localhost:3000/api/geotags HTTP/1.1
